[package]
name = "ex03-creating-lib"
version = "0.1.0"
authors = ["David Silva <srdavidsilva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "colors"
path = "src/colors.rs"