[package]
name = "ex07-show-bigger-and-smaller-without-reordernate"
version = "0.1.0"
authors = ["David Silva <srdavidsilva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
